using BookApp1.Models;
using BookApp1.Views;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System.Collections.ObjectModel;

namespace BookApp1.ViewModels;

public partial class MainPageViewModel : ObservableObject
{
    [ObservableProperty]
    ObservableCollection<Book> bookList;

    [ObservableProperty]
    ObservableCollection<Author> authorsList;

    public RelayCommand AddBookCommand;
    public RelayCommand AddAuthorsCommand;

    public MainPageViewModel()
    {
        BookList = new ObservableCollection<Book>();
        AddBookCommand = new RelayCommand(AddBooks);

        AddBooks();

    }

    private void AddBooks()
    {
        BookList.Add(new Book { Title = "To Kill a Mockingbird", Year = 1960, Publisher = "J.B. Lippincott & Co.", AuthorName = "Harper Lee", Image = "https://m.media-amazon.com/images/I/41j-s9fHJcL.jpg", Description = "The book is set in the 1930s in a small Alabama town and follows the story of a young girl, Scout Finch, as she learns about racial injustice and the importance of standing up for what is right, through her father, Atticus Finch, a lawyer who defends a black man falsely accused of raping a white woman.", Genre = "Fiction, Southern Gothic", Characters = "Scout Finch, Atticus Finch, Jem Finch, Boo Radley, Tom Robinson, Bob Ewell, Calpurnia, Aunt Alexandra", Language = "English", PageNumber = 281, Themes = "Racism, injustice, moral courage, social inequality, coming-of-age, loss of innocence, the power of empathy", Name = "Nelle Harper Lee", Profile = "https://api.time.com/wp-content/uploads/2016/02/harper-lee3.jpeg", Age = "Born on April 28, 1926, and passed away on February 19, 2016, at the age of 89", Bio = "Harper Lee was an American novelist widely known for her novel \"To Kill a Mockingbird.\" The book, which won the Pulitzer Prize in 1961, became a classic of modern American literature and a staple in high school curriculums. Lee's second novel, \"Go Set a Watchman,\" was published in 2015.", Nationality = "American", Education = "University of Alabama", RelevantAwards = "Pulitzer Prize for Fiction (1961), Presidential Medal of Freedom (2007)", OtherJobs = "Lee worked as a reservation clerk for Eastern Airlines in New York City before pursuing a career in writing.", Book1 = "https://upload.wikimedia.org/wikipedia/commons/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg" });
        BookList.Add(new Book { Title = "The mind of a leader", Year = 2003, Publisher = "Harvard Business Review Press", AuthorName = "Rasmus Hougaard and Jacqueline Carter", Image = "https://m.media-amazon.com/images/I/615+drdEOBL.jpg", Description = "\"The Mind of the Leader\" explores what makes a great leader in today's world, emphasizing the importance of mindfulness, self-awareness, and compassion. The book is divided into three parts: Part One focuses on the mindset of the leader, Part Two discusses the actions of the leader, and Part Three explores the development of leadership within an organization. The authors draw on extensive research and real-life examples to provide practical strategies and exercises for developing the qualities of a great leader and applying them to improve personal and organizational performance.", Genre = "Non-fiction, leadership development", Characters = "N/A", Language = "English", PageNumber = 256, Themes = "Mindfulness and self-awareness, Compassion and empathy, Vision and purpose, Development and growth", Name = "Rasmus Hougaard and Jacqueline Carter", Profile = "https://assets.entrepreneur.com/content/1x1/300/20180329150335-Rasmus-Hougaard-jacueline-carter.jpeg", Age = "Unknown", Bio = " Rasmus Hougaard and Jacqueline Carter are co-founders of The Potential Project, a global leadership and organizational development firm. They are also authors of the book \"The Mind of the Leader,\" which provides practical advice on how to develop leadership skills through mindfulness and self-awareness.", Nationality = "Danish and Canadian", Education = "Rasmus Hougaard holds an M.Sc. in Organizational Development and a Ph.D. in Philosophy. Jacqueline Carter holds an MBA from the University of Toronto.", RelevantAwards = "Nan", OtherJobs = "Nan", Book1 = "https://m.media-amazon.com/images/I/615+drdEOBL.jpg" });
        BookList.Add(new Book { Title = "A million to one", Year = 2005, Publisher = "Atticus Creative", AuthorName = "Tony Faggioli", Image = "https://designforwriters.com/wp-content/uploads/2017/10/design-for-writers-book-cover-tf-2-a-million-to-one.jpg", Description = "\"A Million to One\" is a gripping thriller that follows the story of a man named Kyle Fasano, who is given a second chance at life after dying in a car accident. However, as he struggles to come to terms with his new reality, he discovers that his second chance comes with a terrible price. Someone is targeting him and his loved ones, and he must race against time to uncover the truth before it's too late.", Genre = "Fiction, suspense, thriller", Characters = "Kyle Fasano, Emily Fasano, Detective Marcus Reardon, The Assailant", Language = "English", PageNumber = 290, Themes = "Second chances and redemption, Identity and self-discovery, Love and sacrifice, The nature of evil", Name = "Tony Faggioli", Profile = "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/S/amzn-author-media-prod/b9n0op5butqat98r04hg8t8gfp._SX450_.jpg", Age = "Unknown", Bio = "Tony Faggioli is an American author of suspenseful thrillers. His debut novel, \"One In A Million,\" tells the story of a man who wakes up to find that he is the last person left alive on Earth. Faggioli's other books include \"The Snow Globe\" and \"The Darkness Within.\"", Nationality = "American", Education = "The University of Southern California", RelevantAwards = "Nan", OtherJobs = "Careers in both politics and business until", Book1 = "https://designforwriters.com/wp-content/uploads/2017/10/design-for-writers-book-cover-tf-2-a-million-to-one.jpg" });    
        BookList.Add(new Book { Title = "The Vanishing Half", Year = 2020, Publisher = "Riverhead Books", AuthorName = "Brit Bennett", Image = "https://m.media-amazon.com/images/I/91nRWMKV9CL.jpg", Description = "The book follows the lives of twin sisters, Desiree and Stella, who grow up in a small black community in Louisiana. After running away from home at the age of 16, Stella decides to pass as white, while Desiree marries a dark-skinned man and has a daughter with him. The book explores themes of identity, race, and family.", Genre = "Fiction, family saga", Characters = "Desiree, Stella, Jude, Kennedy", Language = "English", PageNumber = 352, Themes = "Race, identity, family, belonging", Name = "Brit Bennett", Profile = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWSrGs75N4-GGM4udnzX32Nf5LmDJTfeTPlet4QiFkNNaLWkVM", Age = "33 ", Bio = " Brit Bennett is an American novelist whose work explores themes of race, identity, and family. Her debut novel, \"The Mothers,\" was a New York Times bestseller, and her second novel, \"The Vanishing Half,\" has been optioned for television by HBO. Bennett has also written for The New Yorker and The Paris Review.", Nationality = "American", Education = "Bennett earned her undergraduate degree from Stanford University and her MFA in fiction from the University of Michigan.", RelevantAwards = "National Book Foundation \"5 Under 35\" (2016), The New York Times \"10 Best Books of 2020\", Women's Prize for Fiction (2021)", OtherJobs = "Nan", Book1 = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1460652458i/28815371.jpg", Book2 = "https://m.media-amazon.com/images/I/91nRWMKV9CL.jpg" });
        BookList.Add(new Book { Title = "The Testaments", Year = 2019, Publisher = "Nan A. Talese", AuthorName = "Margaret Atwood", Image = "https://m.media-amazon.com/images/I/71abcXUrY5L.jpg", Description = "The book is a sequel to \"The Handmaid's Tale\" and is set 15 years after the events of the first book. It follows the lives of three women who are all connected to the oppressive regime of Gilead in different ways.", Genre = "Fiction, dystopian", Characters = "Aunt Lydia, Agnes Jemima, Daisy, Commander Kyle, Becka", Language = "English", PageNumber = 432, Themes = "Oppression, resistance, power, feminism, motherhood, identity", Name = "Margaret Atwood", Profile = "https://cdn.britannica.com/88/207888-050-9B3C1774/Margaret-Atwood-2018.jpg", Age = "18 of november of 1939 (83 years old)", Bio = "Margaret Atwood is a Canadian author, poet, and literary critic. She is best known for her novels and poetry collections, which often explore themes of gender, identity, and environmentalism. Atwood has published more than 50 works of fiction, poetry, and non-fiction and is regarded as one of the most important contemporary writers in Canada and beyond. She has also been an advocate for environmental causes and social justice issues, and has received numerous awards for her contributions to literature and activism.", Nationality = "Canadian", Education = "Atwood obtained her Bachelor's degree in English from Victoria College at the University of Toronto and later pursued graduate studies at Radcliffe College at Harvard University.", RelevantAwards = "The Booker Prize for Fiction for \"The Blind Assassin\" in 2000\r\nThe Arthur C. Clarke Award for Science Fiction for \"The Handmaid's Tale\" in 1987\r\nThe National Book Critics Circle Award for Fiction for \"Alias Grace\" in 1996", OtherJobs = "Atwood has taught at several universities in Canada, the United States, and the United Kingdom, including the University of British Columbia, York University, and the University of Alabama. She has also worked as an editor, literary critic, and political activist, and has been involved with several literary organizations and movements throughout her career.", Book1 = "https://m.media-amazon.com/images/I/61SpcaD4poL.jpg", Book2 = "https://m.media-amazon.com/images/I/51LINF4IF4L._SX316_BO1,204,203,200_.jpg" });
        BookList.Add(new Book { Title = "Such a Fun Age", Year = 2019, Publisher = "G.P. Putnam's Sons", AuthorName = "Kiley Reid", Image = "https://m.media-amazon.com/images/I/71Bm8Pv9nYL.jpg", Description = "The book explores issues of race and privilege through the story of Emira Tucker, a young black woman who works as a babysitter for a wealthy white family.", Genre = "Fiction, social commentary", Characters = "Emira Tucker, Alix Chamberlain, Kelley Copeland, Briar Chamberlain, Peter", Language = "English", PageNumber = 320, Themes = "Race, class, privilege, identity, motherhood, friendship", Name = "Kiley Reid", Profile = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTLEXJKQ2SH0nmb58yYSu8eyITMJSl81OPiYKAQ3siF43-Bv_lL", Age = "born in 1987 (36 years old)", Bio = "Kiley Reid is an American author whose debut novel, \"Such a Fun Age,\" explores issues of race, privilege, and class through the story of a young Black babysitter and the white family she works for. The book was a New York Times bestseller and was longlisted for the 2020 Booker Prize.", Nationality = "American", Education = "Reid earned her MFA from the Iowa Writers' Workshop", RelevantAwards = "NAACP Image Award for Outstanding Literary Work – Debut Author (2021)", OtherJobs = "Reid has worked as a babysitter, a bookseller, and a receptionist, among other jobs.", Book1 = "https://m.media-amazon.com/images/I/91JRfnvs7oL.jpg" });
        BookList.Add(new Book { Title = "A Little Life", Year = 2015, Publisher = "Doubleday", AuthorName = "Hanya Yanagihara", Image = "https://m.media-amazon.com/images/I/81eBp+Fp-jL.jpg", Description = "The book follows the lives of four college friends who move to New York City after graduation and explores the traumas and relationships that shape their lives over several decades.", Genre = "Fiction, family drama", Characters = "Jude St. Francis, Willem Ragnarsson, Malcolm Irvine, JB, Harold Stein", Language = "English", PageNumber = 736, Themes = "Friendship, trauma, abuse, identity, love, sexuality, mental health", Name = "Hanya Yanagihara", Profile = "https://pyxis.nymag.com/v1/imgs/34b/c44/489404bd2459eb238e3f48dea9b4303834-hanya-yanagihara-essay-lede.rvertical.w570.jpg", Age = "20 of september of 1974 (idade 48 anos)", Bio = "Hanya Yanagihara is an American novelist and editor. Her second novel, \"A Little Life,\" was a critical and commercial success, winning several awards and being shortlisted for the Booker Prize. Yanagihara has also worked as an editor at Conde Nast Traveler and T: The New York Times Style Magazine.", Nationality = "American", Education = "Yanagihara earned her undergraduate degree from Smith College and her MFA in fiction from the University of Iowa Writers' Workshop.", RelevantAwards = "Kirkus Prize for Fiction (2015), Lambda Literary Award for Gay Fiction (2016), Women's Prize for Fiction shortlist (2016)", OtherJobs = "Yanagihara has also worked as an editor at Granta and The New Yorker.", Book1 = "https://m.media-amazon.com/images/I/813tySZYHxL.jpg" });
        BookList.Add(new Book { Title = "Normal People", Year = 2018, Publisher = "Faber and Faber", AuthorName = "Sally Rooney", Image = "https://m.media-amazon.com/images/I/719lp7aAAxL.jpg", Description = "The book follows the on-and-off relationship between two young people, Marianne and Connell, as they navigate their way through high school and college.", Genre = "Fiction, romance", Characters = "Marianne Sheridan, Connell Waldron, Lorraine Waldron, Peggy, Jamie", Language = "English", PageNumber = 288, Themes = "Love, class, power, communication, identity, mental health", Name = "Sally Rooney", Profile = "https://static01.nyt.com/images/2021/08/28/books/review/28sallyrooney1/28sallyrooney1-mediumSquareAt3X.jpg", Age = "Born on February 20, 1991 (32 years old)", Bio = "Sally Rooney is an Irish author whose novels explore the complexities of relationships and modern society. Her debut novel, \"Conversations with Friends,\" was critically acclaimed, and her second novel, \"Normal People,\" was adapted into a television series. Rooney has also written for The New York Times and The Guardian.", Nationality = "Irish", Education = "Rooney earned her undergraduate degree from Trinity College Dublin and her M.A. in American Literature from the University of Manchester.", RelevantAwards = "Costa Novel Award (2018), Irish Book Award for Novel of the Year (2018), Women's Prize for Fiction shortlist (2019)", OtherJobs = "Rooney has worked as a teacher and as a waitress.", Book1 = "https://www.faber.co.uk/wp-content/uploads/2022/09/Conversations-with-Friends-1.jpg", Book2 = "https://m.media-amazon.com/images/I/51I3zYamkyL.jpg" });
        BookList.Add(new Book { Title = "The Water Dancer", Year = 2019, Publisher = "One World", AuthorName = "Ta-Nehisi Coates", Image = "https://m.media-amazon.com/images/I/71+W-LNCLgL.jpg", Description = "The book tells the story of Hiram Walker, a slave in Virginia who discovers that he has a supernatural power that can help him escape to freedom.", Genre = "Fiction, historical fiction", Characters = "Hiram Walker, Sophia, Thena, Corrine, Howell Walker", Language = "English", PageNumber = 416, Themes = "Slavery, freedom, memory, identity, family, community", Name = "Ta-Nehisi Coates", Profile = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR45r0uNb_n9RFJBfWEn9QcQlACMp81f74loxVEg9xJjhXvQRpZ", Age = "Born on September 30, 1975 (47 years old)", Bio = "Ta-Nehisi Coates is an American author, journalist, and educator. He is best known for his work on race relations in the United States and has been a vocal critic of systemic racism and white supremacy. Coates has worked as a national correspondent for The Atlantic and has contributed to several other publications, including The New York Times, The Washington Post, and The Village Voice. He has also been a visiting professor at several universities, including MIT and the City University of New York.", Nationality = "American", Education = "Coates attended Howard University but did not complete his degree.", RelevantAwards = "The MacArthur Fellowship (also known as the \"Genius Grant\") in 2015, The National Book Award for Nonfiction for \"Between the World and Me\" in 2015, The Dayton Literary Peace Prize for Nonfiction for \"Between the World and Me\" in 2015", OtherJobs = "In addition to his writing and teaching, Coates has also worked as a consultant for Marvel Comics and has written several comic book series, including \"Black Panther\" and \"Captain America\". He has also been a frequent speaker and commentator on issues of race and social justice.", Book1 = "https://m.media-amazon.com/images/I/81-K4IjzYSL.jpg", Book2 = "https://m.media-amazon.com/images/I/918fubHv68L.jpg" });
        BookList.Add(new Book { Title = "The Silent Patient", Year = 2019, Publisher = "Celadon Books", AuthorName = "Alex Michaelides", Image = "https://m.media-amazon.com/images/I/81dkqO5LAQL.jpg", Description = "\"The Silent Patient\" is a gripping psychological thriller that follows the story of a famous painter named Alicia Berenson, who seemingly has the perfect life until she is found guilty of murdering her husband and then stops speaking. Theo Faber, a criminal psychotherapist, becomes fascinated with Alicia's case and is determined to get her to speak again and find out the truth behind what happened on the night of the murder.", Genre = "Fiction, thriller", Characters = "Alicia Berenson, Theo Fab, Gabriel Berenson, Max Berenson", Language = "English", PageNumber = 336, Themes = "Mental health and trauma, Perception and reality, Obsession and manipulation, Power and control", Name = "Alex Michaelides", Profile = "https://celadonbooks.com/wp-content/uploads/2018/05/Alex-Michaelides-Credit-Charlotte-Knee.gif", Age = "4 of september of 1977 (45 years old)", Bio = "Alex Michaelides is a Cypriot-British author and screenwriter. His debut novel, \"The Silent Patient,\" was a bestseller and won the Goodreads Choice Award for Mystery & Thriller in 2019. Before becoming a full-time writer, Michaelides worked as a screenwriter for both film and television.", Nationality = "Cypriot-British", Education = "Michaelides earned an undergraduate degree in English literature from Cambridge University and a master's degree in screenwriting from the American Film Institute in Los Angeles.", RelevantAwards = "Goodreads Choice Award for Mystery & Thriller (2019)", OtherJobs = "Michaelides worked as a psychotherapist before turning to writing.", Book1 = "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1668782119i/40097951.jpg" });
    }

    [RelayCommand]
    public async void GoToDetail(Book current)
    {
        //await Shell.Current.DisplayAlert("", $"{Username}", "ok");

        await Shell.Current.GoToAsync(nameof(DetailsBookPage),
            new Dictionary<string, Object>
            {
                ["CurrentBook"] = current
            });
    }

    [RelayCommand]

    public async void GoToAuthorsPage(Book currentBook)
    {
        await Shell.Current.GoToAsync(nameof(AuthorsPage),
            new Dictionary<string, Object>
            {
                ["CurrentBook"] = currentBook
            });

    }

    [RelayCommand]
    public async void GoBackLogin()
    {
        await Shell.Current.GoToAsync("///" + nameof(LogIn));
    }
}